# main.yml
name: CI # Continuous Integration
on:
  push:

permissions:
  contents: read

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: rustup component add rustfmt
      - run: cargo fmt --check
  clippy:
    env: 
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
      #    - run: cargo install sqlx-cli
      #    - run: sqlx database create
      #    - run: sqlx migrate run
    - run: cargo clippy --no-deps
